events {
    worker_connections 1024;
}

http {
    server {
        # container port 80;
        listen 80; 

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}